# Homework (Chapter 4) - 201601639 홍승현

- 연습문제 5, 7, 8, 9, 10

## 연습문제 5

<img src="./problem5.png" width="800" height="300">

1. 가중치 행렬 U1, U2, U3, U4를 식(4.1) 처럼 쓰시오.
2. x = (1,0)T가 입력되었을 때 출력 o를 구하시오. 활성함수로 로지스틱 시그모이드를 사용하시오.
3. x = (1,0)T가 입력되었을 때 출력 o를 구하시오. 활성함수로 ReLU를 사용하시오.
4. (1,0)T의 기대 출력이 o = (0,1)T일 때, 현재 1.0인 u3(12) 가중치를 0.9로 줄이면 오류에 어떤 영향을 미치는지 설명하시오.

### 1. 가중치 행렬 U1, U2, U3, U4를 식(4.1) 처럼 쓰시오.


In [3]:
import numpy as np

In [4]:
# DMLP의 가중치 초기화
weights = np.array([[[-0.3, 1.6], [1.0, -1.0], [1.2, -1.1]], [[1.0, 0.7], [1.0, 0.5], [-1.0, 1.0]], [[0.5, -0.1], [-0.8, 0.3], [1.0, 0.4]], [[1.0, -0.2], [0.1, 1.3], [-0.2, -0.4]]])
u1 = weights[0]
u2 = weights[1]
u3 = weights[2]
u4 = weights[3]

In [5]:
from sympy import * # 수식 표현을 위해 임포트

In [6]:
for i in range(len(weights)):
    u = Symbol(f"U^{i+1}")
    mat = Matrix(weights[i], evaluate=False)
    equation = Eq(u, mat, evaluate=False)
    pprint(equation)

     ⎡-0.3  1.6 ⎤
     ⎢          ⎥
U¹ = ⎢1.0   -1.0⎥
     ⎢          ⎥
     ⎣1.2   -1.1⎦
     ⎡1.0   0.7⎤
     ⎢         ⎥
U² = ⎢1.0   0.5⎥
     ⎢         ⎥
     ⎣-1.0  1.0⎦
     ⎡0.5   -0.1⎤
     ⎢          ⎥
U³ = ⎢-0.8  0.3 ⎥
     ⎢          ⎥
     ⎣1.0   0.4 ⎦
     ⎡1.0   -0.2⎤
     ⎢          ⎥
U⁴ = ⎢0.1   1.3 ⎥
     ⎢          ⎥
     ⎣-0.2  -0.4⎦


### 2. x = (1,0)^T가 입력되었을 때 출력 o를 구하시오. 활성함수로 로지스틱 시그모이드를 사용하시오.

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
x = np.array([1, 1, 0]).T
# forward
z1 = np.dot(x, u1)
o1 = sigmoid(z1)
o1 = np.append(1, o1)

z2 = np.dot(o1, u2)
o2 = sigmoid(z2)
o2 = np.append(1, o2)

z3 = np.dot(o2, u3)
o3 = sigmoid(z3)
o3 = np.append(1, o3)

z4 = np.dot(o3, u4)
o4 = sigmoid(z4)

sigmoid_result1 = Eq(Function("Sigmoid")(Symbol("o_1")), Matrix(o4), evaluate=False)
sigmoid_result1


Eq(Sigmoid(o_1), Matrix([
[0.720212909981978],
[0.608070768763911]]))

### 3. x = (1,0)T가 입력되었을 때 출력 o를 구하시오. 활성함수로 ReLU를 사용하시오.

In [9]:
def ReLU(x):
    return np.maximum(0.0, x)

In [10]:
x = np.array([1, 1, 0]).T
# forward
z1 = np.dot(x, u1)
o1 = ReLU(z1)
o1 = np.append(1, o1)

z2 = np.dot(o1, u2)
o2 = ReLU(z2)
o2 = np.append(1, o2)

z3 = np.dot(o2, u3)
o3 = ReLU(z3)
o3 = np.append(1, o3)

z4 = np.dot(o3, u4)
o4 = ReLU(z4)

relu_result1 = Eq(Function("ReLU")(Symbol("o_1")), Matrix(o4), evaluate=False)
relu_result1


Eq(ReLU(o_1), Matrix([
[0.949],
[1.095]]))

### 4. (1,0)T의 기대 출력이 o = (0,1)T일 때, 현재 1.0인 u3(12) 가중치를 0.9로 줄이면 오류에 어떤 영향을 미치는지 설명하시오.

In [11]:
# DMLP의 가중치 초기화
weights = np.array([[[-0.3, 1.6], [1.0, -1.0], [1.2, -1.1]], 
                    [[1.0, 0.7], [1.0, 0.5], [-1.0, 1.0]], 
                    [[0.5, -0.1], [-0.8, 0.3], [0.9, 0.4]], # [1.0, 0.4]를 [0.9, 0.4]로 수정
                    [[1.0, -0.2], [0.1, 1.3], [-0.2, -0.4]]])
u1 = weights[0]
u2 = weights[1]
u3 = weights[2]
u4 = weights[3]

In [12]:
x = np.array([1, 1, 0]).T
# forward
z1 = np.dot(x, u1)
o1 = sigmoid(z1)
o1 = np.append(1, o1)

z2 = np.dot(o1, u2)
o2 = sigmoid(z2)
o2 = np.append(1, o2)

z3 = np.dot(o2, u3)
o3 = sigmoid(z3)
o3 = np.append(1, o3)

z4 = np.dot(o3, u4)
o4 = sigmoid(z4)

sigmoid_result2 = Eq(Function("Sigmoid")(Symbol("o_2")), Matrix(o4), evaluate=False)
sigmoid_result2

Eq(Sigmoid(o_2), Matrix([
[ 0.71983780114165],
[0.602290985036324]]))

In [13]:
x = np.array([1, 1, 0]).T
# forward
z1 = np.dot(x, u1)
o1 = ReLU(z1)
o1 = np.append(1, o1)

z2 = np.dot(o1, u2)
o2 = ReLU(z2)
o2 = np.append(1, o2)

z3 = np.dot(o2, u3)
o3 = ReLU(z3)
o3 = np.append(1, o3)

z4 = np.dot(o3, u4)
o4 = ReLU(z4)

relu_result2 = Eq(Function("ReLU")(Symbol("o_2")), Matrix(o4), evaluate=False)
relu_result2


Eq(ReLU(o_2), Matrix([
[0.9325],
[0.8805]]))

In [14]:
pprint(sigmoid_result1)
pprint(sigmoid_result2)
pprint(relu_result1)
pprint(relu_result2)

              ⎡0.720212909981978⎤
Sigmoid(o₁) = ⎢                 ⎥
              ⎣0.608070768763911⎦
              ⎡0.71983780114165 ⎤
Sigmoid(o₂) = ⎢                 ⎥
              ⎣0.602290985036324⎦
           ⎡0.949⎤
ReLU(o₁) = ⎢     ⎥
           ⎣1.095⎦
           ⎡0.9325⎤
ReLU(o₂) = ⎢      ⎥
           ⎣0.8805⎦


#### 결론

- 기존 o1과 가중치를 갱신한 후의 값인 o2를 비교하자면 기존 값에 비해 소량 감소했음을 알 수 있다.
- 이는 기대출력인 `(0, 1)^T`를 보았을 때, 첫 번째 값은 가까워지고 두 번째 값은 멀어지고 있다고 볼 수 있다.

## 연습문제 7

<img src="./problem7.png" width="800" height="300">

- `그림 4-14`나머지 8개 화소의 값을 계산하시오.

In [15]:
R = np.array([[1, 1, 1], [2, 1, 3], [0, 1, 0]])
G = np.array([[2, 2, 2], [1, 0, 1], [0, 0, 1]])
B = np.array([[0, 3, 0], [1, 0, 1], [1, 0, 0]])

pad_R = np.pad(R, (1, 1))
pad_G = np.pad(G, (1, 1))
pad_B = np.pad(B, (1, 1))
pad_mat = np.array([pad_R, pad_G, pad_B])

# pad_R, pad_G, pad_B
pad_mat

array([[[0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 2, 1, 3, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 2, 2, 2, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [16]:
kernel = np.array([[[0, 0, 0], 
                    [0, 0, 1], 
                    [0, 1, 0]], 
                   [[0, 2, 0], 
                    [0, 2, 0], 
                    [0, 2, 0]], 
                   [[1, 0, 0], 
                    [0, 2, 0], 
                    [0, 0, 1]]])

In [17]:
# pad_R[1:4, 1:4]
s = 1
x = (pad_R.shape[0]-kernel.shape[1])/s+1
assert x.is_integer()
x = int(x)
feature_map = np.zeros((x, x))
for i in range(x):
    for j in range(x):
        sum = 0
        for rgb, ker in zip(pad_mat, kernel):
            sum += np.sum(rgb[i:i+3, j:j+3]*ker)
        feature_map[i][j] = sum

In [18]:
feature_map

array([[ 9., 13.,  9.],
       [ 9.,  8., 13.],
       [ 5.,  1.,  4.]])

## 연습문제 8

<img src="./problem8.png" width="800" height="300">

- `그림 4-8(b)`에서 커널$ \begin{bmatrix} -1 & -1 & -1 \\\\ 0 & 0 & 0 \\\\ 1 & 1 & 1 \end{bmatrix}$을 적용한 결과를 쓰시오. 이 때 0 덧대기를 하고 바이어스로 0.5를 사용하시오.

In [27]:
conv_2d = np.array([[2, 2, 2, 2, 2, 1, 1, 1],
                     [2, 2, 2, 2, 2, 1, 1, 1],
                     [2, 2, 2, 2, 2, 1, 1, 1],
                     [2, 2, 2, 2, 2, 1, 1, 1],
                     [2, 2, 2, 9, 9, 9, 9, 9],
                     [2, 2, 2, 9, 9, 9, 9, 9],
                     [2, 2, 2, 9, 9, 9, 9, 9],
                     [2, 2, 2, 9, 9, 9, 9, 9]])
pad_conv_2d = np.pad(conv_2d, (1, 1))
# conv_2d.shape, pad_conv_2d.shape
pad_conv_2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 2, 2, 2, 2, 1, 1, 1, 0],
       [0, 2, 2, 2, 2, 2, 1, 1, 1, 0],
       [0, 2, 2, 2, 2, 2, 1, 1, 1, 0],
       [0, 2, 2, 2, 2, 2, 1, 1, 1, 0],
       [0, 2, 2, 2, 9, 9, 9, 9, 9, 0],
       [0, 2, 2, 2, 9, 9, 9, 9, 9, 0],
       [0, 2, 2, 2, 9, 9, 9, 9, 9, 0],
       [0, 2, 2, 2, 9, 9, 9, 9, 9, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
kernel = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
kernel.shape

(3, 3)

In [34]:
s = 1
bias = 2
x = (pad_conv_2d.shape[0]-kernel.shape[0])/s+1
assert x.is_integer()
x = int(x)
feature_map2 = np.zeros((x, x))
for i in range(x):
    for j in range(x):
        feature_map2[i][j] = np.sum(pad_conv_2d[i:i+3, j:j+3]*kernel) + bias

In [35]:
feature_map2

array([[  6.,   2.,   2.,   2.,   0.,   0.,   2.,   0.],
       [  8.,   2.,   2.,   2.,  -1.,  -1.,   2.,  -1.],
       [  8.,   2.,   2.,   2.,  -1.,  -1.,   2.,  -1.],
       [  8.,   2.,   9.,   9.,   0.,   0.,   2.,  -9.],
       [  8.,   2.,  16.,  16.,   1.,   1.,   2., -17.],
       [  8.,   2.,  23.,  23.,   2.,   2.,   2., -25.],
       [  8.,   2.,  23.,  23.,   2.,   2.,   2., -25.],
       [  6.,   2.,  16.,  16.,   2.,   2.,   2., -16.]])

## 연습문제 9


- [문제8](#연습문제-8)에서 보폭을 `s = 2`로 설정했을 때 컨볼루션 결과를 쓰시오.

In [36]:
s = 2
bias = 2
x = (pad_conv_2d.shape[0]-kernel.shape[0])/s+1
assert x.is_integer()
x = int(x)
feature_map2 = np.zeros((x, x))
for i in range(x):
    for j in range(x):
        feature_map2[i][j] = np.sum(pad_conv_2d[i:i+3, j:j+3]*kernel) + bias

AssertionError: 

### 결론

- 컽볼루션 연산을 하기 위해서는 `(size-kernel_size)/stride`가 정수여야 하지만 실수가 나오게 된다면 컨볼루션 연산을 할 수 없게 된다.

## 연습문제 10

- [문제8](#연습문제-8)의 결과에 최대 풀링과 평균 풀링을 적용한 결과를 각각 쓰시오. 보폭으로 1을 사용하시오.

In [37]:
# 문제 8의 결과
feature_map2

array([[  6.,   2.,   2.,   2.,   0.,   0.,   2.,   0.],
       [  8.,   2.,   2.,   2.,  -1.,  -1.,   2.,  -1.],
       [  8.,   2.,   2.,   2.,  -1.,  -1.,   2.,  -1.],
       [  8.,   2.,   9.,   9.,   0.,   0.,   2.,  -9.],
       [  8.,   2.,  16.,  16.,   1.,   1.,   2., -17.],
       [  8.,   2.,  23.,  23.,   2.,   2.,   2., -25.],
       [  8.,   2.,  23.,  23.,   2.,   2.,   2., -25.],
       [  6.,   2.,  16.,  16.,   2.,   2.,   2., -16.]])